[32m2023-12-19 15:07:54 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 78c5440d-0278-4015-9ff6-4e4327e1dc8e - 31459 - LOGS_CAPTURED - Started capturing logs in process (pid: 31459).
[32m2023-12-19 15:07:54 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 78c5440d-0278-4015-9ff6-4e4327e1dc8e - 31459 - ReimbursementVsDept - STEP_START - Started execution of step "ReimbursementVsDept".
[32m2023-12-19 15:07:54 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 78c5440d-0278-4015-9ff6-4e4327e1dc8e - ReimbursementVsDept - Loading file from: /Users/nirmalgeorge/dap_dagster_project/DAP-project/govt_employee_analysis/tmpjy9nrer1/storage/JsonLoading using PickledObjectFilesystemIOManager...
[32m2023-12-19 15:07:54 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 78c5440d-0278-4015-9ff6-4e4327e1dc8e - 31459 - ReimbursementVsDept - ASSET_OBSERVATION - DagsterEventType.ASSET_OBSERVATION for step ReimbursementVsDept
[32m2023-12-19 15:07:54 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 78c5440d-0278-4015-9ff6-4e4327e1dc8e - 31459 - ReimbursementVsDept - LOADED_INPUT - Loaded input "JsonLoading" using input manager "io_manager"
[32m2023-12-19 15:07:54 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 78c5440d-0278-4015-9ff6-4e4327e1dc8e - 31459 - ReimbursementVsDept - STEP_INPUT - Got input "JsonLoading" of type "Any". (Type check passed).
[32m2023-12-19 15:07:54 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 78c5440d-0278-4015-9ff6-4e4327e1dc8e - 31459 - ReimbursementVsDept - STEP_FAILURE - Execution of step "ReimbursementVsDept" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "ReimbursementVsDept"::

ValueError: 
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip install -U kaleido


Stack Trace:
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 465, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/dap_dagster_project/DAP-project/govt_employee_analysis/govt_employee_analysis/assets.py", line 75, in ReimbursementVsDept
    fig.write_image(buffer, format="png")
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/plotly/basedatatypes.py", line 3829, in write_image
    return pio.write_image(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/plotly/io/_kaleido.py", line 267, in write_image
    img_data = to_image(
               ^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/plotly/io/_kaleido.py", line 133, in to_image
    raise ValueError(
[0m
