[32m2023-12-18 12:42:11 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5a4401c7-5a95-4a00-8715-118dd2f9e6f8 - 4193 - LOGS_CAPTURED - Started capturing logs in process (pid: 4193).
[32m2023-12-18 12:42:11 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5a4401c7-5a95-4a00-8715-118dd2f9e6f8 - 4193 - LoadingCsv - STEP_START - Started execution of step "LoadingCsv".
[32m2023-12-18 12:42:11 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5a4401c7-5a95-4a00-8715-118dd2f9e6f8 - 4193 - LoadingCsv - STEP_OUTPUT - Yielded output "result" of type "DataFrame". Warning! Type check failed.
[32m2023-12-18 12:42:11 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 5a4401c7-5a95-4a00-8715-118dd2f9e6f8 - 4193 - LoadingCsv - STEP_FAILURE - Execution of step "LoadingCsv" failed.

dagster._core.errors.DagsterTypeCheckDidNotPass: Type check failed for step output "result" - expected type "DataFrame". Description: Value of type <class 'NoneType'> failed type check for Dagster type DataFrame, expected value to be of Python type pandas.core.frame.DataFrame.

Stack Trace:
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_plan.py", line 286, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_step.py", line 485, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event):
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_step.py", line 533, in _type_check_and_store_output
    for output_event in _type_check_output(step_context, step_output_handle, output, version):
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_step.py", line 405, in _type_check_output
    raise DagsterTypeCheckDidNotPass(
[0m
