[32m2023-12-18 20:04:13 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c6bc87cc-2c8e-4af3-b879-51da94fccff7 - 20019 - LOGS_CAPTURED - Started capturing logs in process (pid: 20019).
[32m2023-12-18 20:04:13 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c6bc87cc-2c8e-4af3-b879-51da94fccff7 - 20019 - voucher_dist_Jan2022ToDec2023 - STEP_START - Started execution of step "voucher_dist_Jan2022ToDec2023".
[32m2023-12-18 20:04:13 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c6bc87cc-2c8e-4af3-b879-51da94fccff7 - voucher_dist_Jan2022ToDec2023 - Loading file from: /Users/nirmalgeorge/dap_dagster_project/DAP-project/govt_employee_analysis/tmpjy9nrer1/storage/Merged_data using PickledObjectFilesystemIOManager...
[32m2023-12-18 20:04:13 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c6bc87cc-2c8e-4af3-b879-51da94fccff7 - 20019 - voucher_dist_Jan2022ToDec2023 - ASSET_OBSERVATION - DagsterEventType.ASSET_OBSERVATION for step voucher_dist_Jan2022ToDec2023
[32m2023-12-18 20:04:13 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c6bc87cc-2c8e-4af3-b879-51da94fccff7 - 20019 - voucher_dist_Jan2022ToDec2023 - LOADED_INPUT - Loaded input "Merged_data" using input manager "io_manager"
[32m2023-12-18 20:04:13 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c6bc87cc-2c8e-4af3-b879-51da94fccff7 - 20019 - voucher_dist_Jan2022ToDec2023 - STEP_INPUT - Got input "Merged_data" of type "Any". (Type check passed).
[32m2023-12-18 20:04:13 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - c6bc87cc-2c8e-4af3-b879-51da94fccff7 - 20019 - voucher_dist_Jan2022ToDec2023 - STEP_FAILURE - Execution of step "voucher_dist_Jan2022ToDec2023" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "voucher_dist_Jan2022ToDec2023"::

ValueError: time data '2022-07-11T00:00:00.000' does not match format '%d%m%y' (match)

Stack Trace:
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 465, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/dap_dagster_project/DAP-project/govt_employee_analysis/govt_employee_analysis/assets.py", line 204, in voucher_dist_Jan2022ToDec2023
    data_df['date'] = pd.to_datetime(data_df['payment_date'], format='%d%m%y')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 1064, in to_datetime
    cache_array = _maybe_cache(arg, format, cache, convert_listlike)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 229, in _maybe_cache
    cache_dates = convert_listlike(unique_dates, format)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 430, in _convert_listlike_datetimes
    res = _to_datetime_with_format(
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 538, in _to_datetime_with_format
    res = _array_strptime_with_fallback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 473, in _array_strptime_with_fallback
    result, timezones = array_strptime(arg, fmt, exact=exact, errors=errors)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/tslibs/strptime.pyx", line 150, in pandas._libs.tslibs.strptime.array_strptime
[0m
