[32m2023-12-18 14:48:45 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d8768fb7-00e6-4c9a-bf62-04a80f581229 - 8711 - LOGS_CAPTURED - Started capturing logs in process (pid: 8711).
[32m2023-12-18 14:48:45 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d8768fb7-00e6-4c9a-bf62-04a80f581229 - 8711 - PercentageFullTimeAndPartTimePerDepartment - STEP_START - Started execution of step "PercentageFullTimeAndPartTimePerDepartment".
[32m2023-12-18 14:48:45 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d8768fb7-00e6-4c9a-bf62-04a80f581229 - PercentageFullTimeAndPartTimePerDepartment - Loading file from: /Users/nirmalgeorge/dap_dagster_project/DAP-project/govt_employee_analysis/tmpjy9nrer1/storage/LoadingCsv using PickledObjectFilesystemIOManager...
[32m2023-12-18 14:48:45 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d8768fb7-00e6-4c9a-bf62-04a80f581229 - 8711 - PercentageFullTimeAndPartTimePerDepartment - ASSET_OBSERVATION - DagsterEventType.ASSET_OBSERVATION for step PercentageFullTimeAndPartTimePerDepartment
[32m2023-12-18 14:48:45 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d8768fb7-00e6-4c9a-bf62-04a80f581229 - 8711 - PercentageFullTimeAndPartTimePerDepartment - LOADED_INPUT - Loaded input "LoadingCsv" using input manager "io_manager"
[32m2023-12-18 14:48:45 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d8768fb7-00e6-4c9a-bf62-04a80f581229 - 8711 - PercentageFullTimeAndPartTimePerDepartment - STEP_INPUT - Got input "LoadingCsv" of type "Any". (Type check passed).
[32m2023-12-18 14:48:45 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - d8768fb7-00e6-4c9a-bf62-04a80f581229 - 8711 - PercentageFullTimeAndPartTimePerDepartment - STEP_FAILURE - Execution of step "PercentageFullTimeAndPartTimePerDepartment" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "PercentageFullTimeAndPartTimePerDepartment"::

TypeError: unhashable type: 'dict'

Stack Trace:
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 465, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/dap_dagster_project/DAP-project/govt_employee_analysis/govt_employee_analysis/assets.py", line 127, in PercentageFullTimeAndPartTimePerDepartment
    p = ax.bar(departments, employment_counts, width, label="Employment Types", bottom=bottom)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/__init__.py", line 1442, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 2392, in bar
    self._process_unit_info(
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 2549, in _process_unit_info
    axis.update_units(data)
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/axis.py", line 1675, in update_units
    default = self.converter.default_units(data, self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/category.py", line 105, in default_units
    axis.set_units(UnitData(data))
                   ^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/category.py", line 181, in __init__
    self.update(data)
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/category.py", line 214, in update
    for val in OrderedDict.fromkeys(data):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
[0m
