[32m2023-12-19 15:33:31 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 63b06f6d-2574-4a62-9730-9a9aa6b7eaa8 - 32570 - LOGS_CAPTURED - Started capturing logs in process (pid: 32570).
[32m2023-12-19 15:33:31 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 63b06f6d-2574-4a62-9730-9a9aa6b7eaa8 - 32570 - ReimbursementVsDept - STEP_START - Started execution of step "ReimbursementVsDept".
[32m2023-12-19 15:33:31 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 63b06f6d-2574-4a62-9730-9a9aa6b7eaa8 - ReimbursementVsDept - Loading file from: /Users/nirmalgeorge/dap_dagster_project/DAP-project/govt_employee_analysis/tmpjy9nrer1/storage/JsonLoading using PickledObjectFilesystemIOManager...
[32m2023-12-19 15:33:31 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 63b06f6d-2574-4a62-9730-9a9aa6b7eaa8 - 32570 - ReimbursementVsDept - ASSET_OBSERVATION - DagsterEventType.ASSET_OBSERVATION for step ReimbursementVsDept
[32m2023-12-19 15:33:31 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 63b06f6d-2574-4a62-9730-9a9aa6b7eaa8 - 32570 - ReimbursementVsDept - LOADED_INPUT - Loaded input "JsonLoading" using input manager "io_manager"
[32m2023-12-19 15:33:31 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 63b06f6d-2574-4a62-9730-9a9aa6b7eaa8 - 32570 - ReimbursementVsDept - STEP_INPUT - Got input "JsonLoading" of type "Any". (Type check passed).
[32m2023-12-19 15:33:31 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 63b06f6d-2574-4a62-9730-9a9aa6b7eaa8 - 32570 - ReimbursementVsDept - STEP_FAILURE - Execution of step "ReimbursementVsDept" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "ReimbursementVsDept"::

TypeError: 'value' must be an instance of str or bytes, not a float

Stack Trace:
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 465, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/dap_dagster_project/DAP-project/govt_employee_analysis/govt_employee_analysis/assets.py", line 70, in ReimbursementVsDept
    plt.scatter(reimburesment_df['department'], reimburesment_df['amount'])
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/pyplot.py", line 2862, in scatter
    __ret = gca().scatter(
            ^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/__init__.py", line 1442, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 4578, in scatter
    x, y = self._process_unit_info([("x", x), ("y", y)], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 2549, in _process_unit_info
    axis.update_units(data)
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/axis.py", line 1675, in update_units
    default = self.converter.default_units(data, self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/category.py", line 105, in default_units
    axis.set_units(UnitData(data))
                   ^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/category.py", line 181, in __init__
    self.update(data)
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/category.py", line 216, in update
    _api.check_isinstance((str, bytes), value=val)
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/matplotlib/_api/__init__.py", line 93, in check_isinstance
    raise TypeError(
[0m
